import NavBar from "@/components/NavBar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LayoutContainer from "@/components/LayoutContainer";
import { cn } from "@/lib/Utils";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen w-full bg-white dark:bg-slate-900 dark:text-white text-slate-800 opacity-85",
          inter.className
        )}
      >
        <LayoutContainer>
          <NavBar />
          {children}
        </LayoutContainer>
      </body>
    </html>
  );
}
